stages:
  - lint
  - build
  - deploy

lint:
  image: harbor.ulbricht.casa/imanuel/trunk-docker-base-image:latest
  stage: lint
  script:
    - cargo clippy -p yew-cosmo-docs
    - cargo check

build:
  image: harbor.ulbricht.casa/imanuel/trunk-docker-base-image:latest
  stage: build
  script:
    - trunk build --release

deploy:
  image: harbor.ulbricht.casa/imanuel/trunk-docker-base-image:latest
  stage: deploy
  script:
    - cargo publish --token ${CARGO_REGISTRY_TOKEN}
  rules:
    - if: $CI_COMMIT_TAG

pages:
  image: harbor.ulbricht.casa/imanuel/trunk-docker-base-image:latest
  stage: deploy
  script:
    - trunk build --release --dist="public"
    - echo "/* /index.html 200" > public/_redirects
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_TAG