stages:
  - lint
  - build
  - deploy

lint:
  image: quay.imanuel.dev/imanuel/trunk-docker-base-image:latest
  stage: lint
  script:
    - cargo clippy -p yew-cosmo --no-deps
    - cargo clippy -p yew-cosmo-docs --no-deps
    - cargo check

build:
  image: quay.imanuel.dev/imanuel/trunk-docker-base-image:latest
  stage: build
  script:
    - trunk build --release

deploy:
  image: quay.imanuel.dev/imanuel/trunk-docker-base-image:latest
  stage: deploy
  script:
    - cargo publish --token ${CARGO_REGISTRY_TOKEN}
  rules:
    - if: $CI_COMMIT_TAG

pages:
  image: quay.imanuel.dev/imanuel/trunk-docker-base-image:latest
  stage: deploy
  script:
    - trunk build --release --dist="public"
    - echo "/* /index.html 200" > public/_redirects
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_TAG