.install-dependencies:
  before_script:
    - apk add musl-dev
    - rustup target add wasm32-unknown-unknown
    - cargo install --lock trunk
    - cargo install

lint:
  extends:
    - .install-dependencies
  image: quay.imanuel.dev/dockerhub/library---rust:1.70-alpine3.18
  stage: lint
  script:
    - cargo check

build:
  extends:
    - .install-dependencies
  image: quay.imanuel.dev/dockerhub/library---rust:1.70-alpine3.18
  stage: build
  script:
    - trunk build --release

deploy:
  extends:
    - .install-dependencies
  image: quay.imanuel.dev/dockerhub/library---rust:1.70-alpine3.18
  stage: deploy
  script:
    - cargo build
    - cargo publish --token ${CARGO_REGISTRY_TOKEN}
  rules:
    - if: $CI_COMMIT_TAG

pages:
  extends:
    - .install-dependencies
  image: quay.imanuel.dev/dockerhub/library---rust:1.70-alpine3.18
  stage: deploy
  script:
    - trunk build --release --dist="public"
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_TAG