.base-cache:
  image: registry.ulbricht.casa/docker-images/trunk-docker-base-image:latest
  variables: 
    CARGO_HOME: $CI_PROJECT_DIR/.cargo
  cache: 
    key: $CI_PROJECT_NAME
    paths: 
      - $CI_PROJECT_DIR/dist/
      - $CI_PROJECT_DIR/target/
      - $CI_PROJECT_DIR/.cargo/
      - $CI_PROJECT_DIR/Cargo.lock

stages:
  - lint
  - build
  - deploy

lint:
  extends: 
    - .base-cache
  stage: lint
  script:
    - cargo clippy -p yew-cosmo-docs --release

build:
  extends: 
    - .base-cache
  stage: build
  script:
    - trunk build --release --dist="public"

deploy:
  image: registry.ulbricht.casa/docker-images/trunk-docker-base-image:latest
  stage: deploy
  script:
    - cargo publish --token ${CARGO_REGISTRY_TOKEN}
  rules:
    - if: $CI_COMMIT_TAG

pages:
  extends: 
    - .base-cache
  stage: deploy
  script:
    - trunk build --release --dist="public"
    - echo "/* /index.html 200" > public/_redirects
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_TAG