[package]
name = "yew-cosmo"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "1.4.0", features = ["js", "v4"] }
stylist = { version = "0.12.1", features = ["yew", "yew_use_style"] }
yew = "0.20.0"
yew-router = "0.17.0"
yew-hooks = "0.2.0"
yew-feather = "1.0.0"
web-sys = { version = "0.3.64", features = ["HtmlSelectElement"] }
getrandom = "0.2.10"
rand = "0.8.5"
log = "0.4.19"
gloo = "0.8.1"
wasm-bindgen = "0.2.87"
color-art = "0.3.2"
chrono = "0.4.26"