[package]
name = "yew-cosmo"
version = "0.14.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "1.4", features = ["js", "v4"] }
stylist = { version = "0.12", features = ["yew", "yew_use_style"] }
yew = "0.20"
yew-router = { version = "0.17", optional = true }
yew-hooks = "0.2"
yew-feather = "1.0"
web-sys = { version = "0.3", features = ["HtmlSelectElement", "Element"] }
getrandom = "0.2"
rand = "0.8"
log = "0.4"
gloo = "0.9"
wasm-bindgen = "0.2"
color-art = "0.3"
chrono = "0.4"

[workspace]
members = [
    "docs"
]

[features]
default = ["with-yew-router"]
with-yew-router = ["dep:yew-router"]
